In [2]:
import plotly.express as px
import pandas as pd

In [3]:
df = pd.read_csv('D:\Downloads\city_sustainability_geospatial(1).csv')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\LapShop\AppData\Local\Temp\ipykernel_4544\3631472432.py:1: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv('D:\Downloads\city_sustainability_geospatial(1).csv')

In [4]:
df.head()

,city,country,continent,iso_alpha3,latitude,longitude,population_millions,avg_temp_c,co2_tons_per_capita,renewable_energy_share,air_quality_index,traffic_congestion_index,is_coastal
0,City_1,United States,North America,USA,30.2176,-92.4343,7.55,26.7,7.70,18.3,79.7,75.6,No
1,City_2,Canada,North America,CAN,52.3668,-75.3981,11.35,21.8,9.14,37.1,45.4,60.4,Yes
2,City_3,Saudi Arabia,Asia,SAU,26.9573,42.2140,7.27,27.5,1.22,25.2,36.5,41.5,No
3,City_4,South Africa,Africa,ZAF,-29.1878,27.4098,8.94,29.8,5.74,34.5,58.4,98.0,No
4,City_5,South Africa,Africa,ZAF,-28.7371,18.8952,8.89,10.5,1.45,23.1,45.0,83.3,No

In [5]:
df.shape

(300, 13)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   city                      300 non-null    str
 1   country                   300 non-null    str
 2   continent                 300 non-null    str
 3   iso_alpha3                300 non-null    str
 4   latitude                  300 non-null    float64
 5   longitude                 300 non-null    float64
 6   population_millions       300 non-null    float64
 7   avg_temp_c                300 non-null    float64
 8   co2_tons_per_capita       300 non-null    float64
 9   renewable_energy_share    300 non-null    float64
 10  air_quality_index         300 non-null    float64
 11  traffic_congestion_index  300 non-null    float64
 12  is_coastal                300 non-null    str
dtypes: float64(8), str(5)
memory usage: 30.6 KB

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
latitude,300.0,24.184147,27.382746,-33.3270,14.95980,27.4628,49.187225,59.9838
longitude,300.0,5.956065,64.991753,-129.6253,-50.33425,19.0132,43.205725,119.6486
population_millions,300.0,6.993600,4.155893,0.3000,3.36750,6.9300,10.267500,14.9800
avg_temp_c,300.0,17.929333,7.894904,5.0000,10.50000,18.3000,25.425000,30.0000
co2_tons_per_capita,300.0,5.375133,2.243340,0.5000,3.81750,5.5350,6.810000,11.4500
renewable_energy_share,300.0,32.604000,13.044110,5.0000,23.32500,31.2000,42.000000,67.7000
air_quality_index,300.0,71.301333,15.481954,21.0000,61.60000,70.3000,81.175000,120.6000
traffic_congestion_index,300.0,65.808667,19.346018,13.0000,52.80000,64.5500,81.225000,100.0000

In [11]:
df.columns

Index(['city', 'country', 'continent', 'iso_alpha3', 'latitude', 'longitude',
       'population_millions', 'avg_temp_c', 'co2_tons_per_capita',
       'renewable_energy_share', 'air_quality_index',
       'traffic_congestion_index', 'is_coastal'],
      dtype='str')

In [5]:
fig = px.scatter(df , x='co2_tons_per_capita',
                 y='air_quality_index',
                 color='continent',
                 size='population_millions',
                 hover_name='city',
                 hover_data=['is_coastal','avg_temp_c'])
fig.show()

In [16]:
df.columns

Index(['city', 'country', 'continent', 'iso_alpha3', 'latitude', 'longitude',
       'population_millions', 'avg_temp_c', 'co2_tons_per_capita',
       'renewable_energy_share', 'air_quality_index',
       'traffic_congestion_index', 'is_coastal'],
      dtype='str')

In [6]:
px.histogram(df,x='air_quality_index',nbins=30,
             color='continent',
             marginal='box',
               title='Distribution of Air Quality Index by continent')

In [7]:
fig = px.box(df , y='renewable_energy_share',
             x='continent',
             points='all')
fig.show()

In [8]:
fig = px.violin(df , y='renewable_energy_share',
             x='continent',
             points='all',
             color='is_coastal')
fig.show()

In [9]:
continent_counts = df['continent'].value_counts().reset_index()
continent_counts

       continent  count
0           Asia     88
1         Africa     66
2  North America     60
3         Europe     54
4  South America     32

In [10]:
fig = px.bar(continent_counts , y='count',x='continent')
fig.show()

In [11]:
ct = pd.crosstab(df['continent'],df['is_coastal']).reset_index()
ct

is_coastal      continent  No  Yes
0                  Africa  38   28
1                    Asia  59   29
2                  Europe  38   16
3           North America  34   26
4           South America  18   14

In [12]:
fig = px.bar(pd.crosstab(df['continent'],df['is_coastal']),barmode='group')
fig.show()

In [13]:
#another method 
dff = df.groupby(['continent','is_coastal']).size().reset_index(name='count')
dff

       continent is_coastal  count
0         Africa         No     38
1         Africa        Yes     28
2           Asia         No     59
3           Asia        Yes     29
4         Europe         No     38
5         Europe        Yes     16
6  North America         No     34
7  North America        Yes     26
8  South America         No     18
9  South America        Yes     14

In [14]:
fig = px.bar(dff ,x='continent',y='count',barmode='group',
             color='is_coastal')
fig.show()

In [15]:
df.columns.to_list()

['city',
 'country',
 'continent',
 'iso_alpha3',
 'latitude',
 'longitude',
 'population_millions',
 'avg_temp_c',
 'co2_tons_per_capita',
 'renewable_energy_share',
 'air_quality_index',
 'traffic_congestion_index',
 'is_coastal']

In [16]:
fig = px.scatter_geo(df , lon='longitude',lat='latitude',
                     color='continent',
                     projection='natural earth',
                     hover_name='city',
                     hover_data=['avg_temp_c','air_quality_index',
                               'is_coastal'])
fig.show()

In [72]:
df.columns

Index(['city', 'country', 'continent', 'iso_alpha3', 'latitude', 'longitude',
       'population_millions', 'avg_temp_c', 'co2_tons_per_capita',
       'renewable_energy_share', 'air_quality_index',
       'traffic_congestion_index', 'is_coastal'],
      dtype='str')

In [17]:
country_stats = df.groupby('iso_alpha3').agg({
    'population_millions':'sum',
    'co2_tons_per_capita':'mean',
    'air_quality_index':'mean',
    'renewable_energy_share':'mean'
}).reset_index()

In [19]:
fig = px.choropleth( country_stats, locations='iso_alpha3',
                    color='population_millions',
                    projection='natural earth',
                    hover_data=['population_millions',
                               'air_quality_index' ])
fig.show()

In [20]:
fig = px.scatter_map(df,
               lat='latitude',
                lon='longitude')
fig.show()